title: Decision Theory Problems
description: A collection of decision theory problems and their solutions
theme: just-the-docs

url: https://mogar.github.io/DecisionTheory

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
