title: Decision Theory Problems
description: A collection of decision theory problems and their solutions
theme: just-the-docs

url: https://mogar.github.io/DecisionTheory

color_scheme: dark

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
